services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "80:80"
    command: >
      sh -c "composer install && apache2-foreground"
    volumes:
      - ./src:/var/www/src
      - ./public:/var/www/html
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./doctrine.php:/var/www/doctrine.php
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docfav
      MYSQL_USER: docfav
      MYSQL_PASSWORD: Spain.2025
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: